# run on container environment
sudo: false

language: php

cache:
    apt: true
    directories:
        - $HOME/.npm
        - vendor
        - $HOME/.composer/cache

notifications:
    email:
        on_success: change
        on_failure: always

php:
    - 7.2
    - 7.1
    - 7.0

env:
    # latest:
    - WP_VERSION=latest
    # nightly:
    - WP_VERSION=nightly

matrix:
    fast_finish: true
    allow_failures:
        # allow failures on nightlies:
        - env: WP_VERSION=nightly

install:
    - travis_retry composer install --no-interaction

before_script:
    - travis_retry bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - ./vendor/bin/phpcs -n -p -s --colors .
